### ISSUE TITLE
Example has misleading types in responseData. (typo in documentation)

### ISSUE THREAD

**Issue by mbejda** [hellobloom/share-kit#19]
## Typo in documentation
Documentation implies the responseData type action is string which is incorrect. It should be
type Action. 

Error thrown by the IDE because of incorrect type. 
https://github.com/hellobloom/share-kit/blame/master/README.md#L94
<img width="935" alt="screen shot 2018-11-05 at 1 24 31 pm" src="https://user-images.githubusercontent.com/5429780/48018180-2dd44080-e0fe-11e8-816f-5085c3194acc.png">

The example should include the correct type like so: 
```javascript
 
      const requestData: RequestData = {
      action: <Action>'request_attestation_data',
      token: "0x8f31e48a585fd12ba58e70e03292cac712cbae39bc7eb980ec189aa88e24d04",
      url: "https://bloom.co/api/receiveData",
      org_logo_url: 'https://bloom.co/images/notif/bloom-logo.png',
      org_name: 'Bloom',
      org_usage_policy_url: 'https://bloom.co/legal/terms',
      org_privacy_policy_url: 'https://bloom.co/legal/privacy',
      types: ['full-name', 'phone', 'email'],
    }
```

**Comment by JaceHensley** [comment]
fix in #20
