### ISSUE TITLE
sharekit not compiling correctly

### ISSUE THREAD

**Issue by mbejda** [hellobloom/share-kit#21]
**Type bug**
Sharekit code on npmjs contains .git folder while the master repo does not. 
npm install fails because `.git`. 
<img width="969" alt="screen shot 2018-11-05 at 3 03 41 pm" src="https://user-images.githubusercontent.com/5429780/48023518-02f0e900-e10c-11e8-8061-5b76eda93cd2.png">

**Comment by JaceHensley** [comment]
Hmm this is quite odd as `.git` should always be left our of the published npm package see [here](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). But we'll explicitly add it to `.npmignore` and see if that fixes it. If not I'm open to suggestions on how to fix this.

**Comment by JaceHensley** [comment]
@mbejda can you point to v2.0.2? Just published and it should take care of this issue

**Comment by mbejda** [comment]
@JaceHensley I looked through the contents and you are correct. The `.git` folder not in the module and the module installs fine. However, the latest appears to be unstable in the sense that it does not compile nicely. The previous version compiled OK. 

<img width="1067" alt="screen shot 2018-11-06 at 2 06 34 pm" src="https://user-images.githubusercontent.com/5429780/48087421-452e2f00-e1cd-11e8-969f-d3150ef4d124.png">

I went into the node modules directory to see whats going and it appears that certain files are missing.  Here is a snapshot of the directory. 
<img width="385" alt="screen shot 2018-11-06 at 2 08 15 pm" src="https://user-images.githubusercontent.com/5429780/48087525-8a526100-e1cd-11e8-98af-018772c4a189.png">

The code inside the `index.js` file
```javascript
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
var manageRequestQRCode_1 = require("./src/manageRequestQRCode");
exports.createRequestQRCode = manageRequestQRCode_1.createRequestQRCode;
exports.updateRequestQRCode = manageRequestQRCode_1.updateRequestQRCode;
exports.removeRequestQRCode = manageRequestQRCode_1.removeRequestQRCode;
var RequestQRCode_1 = require("./src/RequestQRCode");
exports.RequestQRCode = RequestQRCode_1.RequestQRCode;
var types_1 = require("./src/types");
exports.Action = types_1.Action;
var BloomLogo_1 = require("./src/BloomLogo");
exports.BloomLogo = BloomLogo_1.BloomLogo;
var util = __importStar(require("./src/util"));
exports.util = util;
//# sourceMappingURL=index.js.map
```
It appears that the paths are incorrect. .
I also noticed the tsconfig is missing `tsx` support. 
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by mbejda** [comment]
Confirmed that `v2.0.1` compiles fine and seems to be stable. It also seems to have all the files it needs to work. 
<img width="545" alt="screen shot 2018-11-06 at 2 32 54 pm" src="https://user-images.githubusercontent.com/5429780/48088807-e7034b00-e1d0-11e8-908a-76c3a8d127bd.png">

**Comment by JaceHensley** [comment]
Ah jeez, I'm not sure how 2.0.2 got broken like that. Can you try again with 2.0.3?
